Fixes #24939 - Show id of the report on command line
theforeman/foreman_scap_client pull request #22
Opened 2018-09-14 09:37 UTC by xprazak2

2018-09-14 09:38 UTC, xprazak2 commented
Needs https://github.com/theforeman/smart_proxy_openscap/pull/63 to work

2018-10-11 11:16 UTC, ares requested changes
two small things, then good to go in

2018-10-11 11:16 UTC, ares commented on lib/foreman_scap_client/client.rb
> +      puts "Report not uploaded from proxy to Foreman server, cause: #{parsed['result']}"
missing space causing wrong indentation

2018-10-11 11:16 UTC, ares commented on lib/foreman_scap_client/client.rb
> +     parsed = JSON.parse(response.body)
what if proxy runs older version of smart_proxy_openscap and does not response with valid JSON? should we rescue the parsing error? I'm getting following error on such scenario

```
Uploading results to https://foreman.example.tst:8443/compliance/arf/5
Upload failed: A JSON text must at least contain two octets!
```

2018-10-11 11:36 UTC, xprazak2 commented
I rescue the parsing error and print nothing.

2018-10-11 13:13 UTC, ares approved these changes

2018-10-11 13:13 UTC, ares commented
Thanks @xprazak2, merging!

2018-10-11 13:13 UTC, merged